Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu-14.04-amd64"
  config.vm.box_check_update = false

  config.vm.network "forwarded_port", guest: 5432, host: 5432
  config.vm.network "private_network", ip: "192.168.50.1",
    virtualbox__intnet: "vms-only"

  config.vm.synced_folder "./data", "/vagrant_data"

  config.vm.provision "shell", inline: <<-SHELL
      chmod +x /vagrant_data/setup.sh
      /bin/bash /vagrant_data/setup.sh

		  chmod +x /vagrant_data/db/init-db.sh
		  /bin/bash /vagrant_data/db/init-db.sh
  SHELL
end